### ISSUE TITLE
Data to reproduce tutorials

### ISSUE THREAD

**Issue by DanielLenz** [mirapy-org/tutorials#7]
I couldn't find the data to re-run the notebooks; could you add them to the repo or point out where to find them? Thank you! (https://github.com/openjournals/joss-reviews/issues/1557)

**Comment by swapsha96** [comment]
Datasets:

[HTRU1 Dataset](http://www.jb.man.ac.uk/research/ascaife/htru1-batches-py.tar.gz)
[X-Ray Binaries](https://github.com/mirapy-org/mirapy/tree/master/mirapy/dataset/XRayBinary)
[Sunspotter All Clear Dataset (visualization)](https://zenodo.org/record/1478966)
[Messier's catalog images](https://github.com/mirapy-org/messier-catalog-images/tree/master/data)

OGLE and ATLAS datasets have a specific way to download and clean them. I can share them later.

**Comment by DanielLenz** [comment]
Great, thank you! Could you add these links e.g. to the README so that others can quickly find the data to re-run the tutorials?
If the file size allows that, it would be great to have all data be a part of the repo, such that the project doesn't rely on external links & data.

**Comment by swapsha96** [comment]
I have added links in README as per your suggestion. Regarding hosting files, since I do not own any of these files, I prefer redirecting them to the original sources which often include citations. As the data size will grow, I would probably host the files in services like AWS but I do not have such plans right now.

**Comment by DanielLenz** [comment]
Perfect, thanks!
